<a href="https://colab.research.google.com/github/rachocr/CCDATSCL_EXERCISES/blob/main/Exercise4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Exercise 4

This exercise focuses on data visualization and interpretation using a real-world COVID-19 dataset. The dataset contains daily records of confirmed cases, deaths, recoveries, and active cases across countries and regions, along with temporal and geographic information.
The goal of this exercise is not only to create charts, but to choose appropriate visualizations, apply correct data aggregation, and draw meaningful insights from the data. You will work with time-based, categorical, numerical, and geographic variables, and you are expected to think critically about how design choices affect interpretation.

Your visualizations should follow good practices:
- Use clear titles, axis labels, and legends
- Choose chart types appropriate to the data and question
- Avoid misleading scales or cluttered designs
- Clearly explain patterns, trends, or anomalies you observe

Unless stated otherwise, you may filter, aggregate, or group the data as needed.

<img src="https://d3i6fh83elv35t.cloudfront.net/static/2020/03/Screen-Shot-2020-03-05-at-6.29.29-PM-1024x574.png"/>

In [12]:
import kagglehub
import os
import pandas as pd

import plotly.express as px
import seaborn as sns
import matplotlib.pyplot as plt

# Download latest version
path = kagglehub.dataset_download("imdevskp/corona-virus-report")

print("Path to dataset files:", path)

Using Colab cache for faster access to the 'corona-virus-report' dataset.
Path to dataset files: /kaggle/input/corona-virus-report

In [2]:
if os.path.isdir(path):
  print(True)

contents = os.listdir(path)
contents

mydataset = path + "/" + contents[0]
mydataset


df = pd.read_csv(mydataset)

True

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 49068 entries, 0 to 49067
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Province/State  14664 non-null  object
 1   Country/Region  49068 non-null  object
 2   Lat             49068 non-null  float64
 3   Long            49068 non-null  float64
 4   Date            49068 non-null  object
 5   Confirmed       49068 non-null  int64
 6   Deaths          49068 non-null  int64
 7   Recovered       49068 non-null  int64
 8   Active          49068 non-null  int64
 9   WHO Region      49068 non-null  object
dtypes: float64(2), int64(4), object(4)
memory usage: 3.7+ MB

In [4]:
df.head()

,Province/State,Country/Region,Lat,Long,Date,Confirmed,Deaths,Recovered,Active,WHO Region
0,NaN,Afghanistan,33.93911,67.709953,2020-01-22,0,0,0,0,Eastern Mediterranean
1,NaN,Albania,41.15330,20.168300,2020-01-22,0,0,0,0,Europe
2,NaN,Algeria,28.03390,1.659600,2020-01-22,0,0,0,0,Africa
3,NaN,Andorra,42.50630,1.521800,2020-01-22,0,0,0,0,Europe
4,NaN,Angola,-11.20270,17.873900,2020-01-22,0,0,0,0,Africa

In [42]:
df.query("`Country/Region` == 'Philippines'")

,Province/State,Country/Region,Lat,Long,Date,Confirmed,Deaths,Recovered,Active,WHO Region
180,NaN,Philippines,12.879721,121.774017,2020-01-22,0,0,0,0,Western Pacific
441,NaN,Philippines,12.879721,121.774017,2020-01-23,0,0,0,0,Western Pacific
702,NaN,Philippines,12.879721,121.774017,2020-01-24,0,0,0,0,Western Pacific
963,NaN,Philippines,12.879721,121.774017,2020-01-25,0,0,0,0,Western Pacific
1224,NaN,Philippines,12.879721,121.774017,2020-01-26,0,0,0,0,Western Pacific
...,...,...,...,...,...,...,...,...,...,...
47943,NaN,Philippines,12.879721,121.774017,2020-07-23,74390,1871,24383,48136,Western Pacific
48204,NaN,Philippines,12.879721,121.774017,2020-07-24,76444,1879,24502,50063,Western Pacific
48465,NaN,Philippines,12.879721,121.774017,2020-07-25,78412,1897,25752,50763,Western Pacific
48726,NaN,Philippines,12.879721,121.774017,2020-07-26,80448,1932,26110,52406,Western Pacific
48987,NaN,Philippines,12.879721,121.774017,2020-07-27,82040,1945,26446,53649,Western Pacific

## A. Time-Based Visualizations

1. Global Trend `(5 pts)`

Aggregate the data by Date and create a line chart showing the global number of confirmed COVID-19 cases over time.

In [82]:
df['Country/Region'].unique()

array(['Afghanistan', 'Albania', 'Algeria', 'Andorra', 'Angola',
       'Antigua and Barbuda', 'Argentina', 'Armenia', 'Australia',
       'Austria', 'Azerbaijan', 'Bahamas', 'Bahrain', 'Bangladesh',
       'Barbados', 'Belarus', 'Belgium', 'Benin', 'Bhutan', 'Bolivia',
       'Bosnia and Herzegovina', 'Brazil', 'Brunei', 'Bulgaria',
       'Burkina Faso', 'Cabo Verde', 'Cambodia', 'Cameroon', 'Canada',
       'Central African Republic', 'Chad', 'Chile', 'China', 'Colombia',
       'Congo (Brazzaville)', 'Congo (Kinshasa)', 'Costa Rica',
       "Cote d'Ivoire", 'Croatia', 'Cuba', 'Cyprus', 'Czechia', 'Denmark',
       'Greenland', 'Djibouti', 'Dominican Republic', 'Ecuador', 'Egypt',
       'El Salvador', 'Equatorial Guinea', 'Eritrea', 'Estonia',
       'Eswatini', 'Ethiopia', 'Fiji', 'Finland', 'France', 'Gabon',
       'Gambia', 'Georgia', 'Germany', 'Ghana', 'Greece', 'Guatemala',
       'Guinea', 'Guyana', 'Haiti', 'Holy See', 'Honduras', 'Hungary',
       'Iceland', 'India', 'Indonesia', 'Iran', 'Iraq', 'Ireland',
       'Israel', 'Italy', 'Jamaica', 'Japan', 'Jordan', 'Kazakhstan',
       'Kenya', 'South Korea', 'Kuwait', 'Kyrgyzstan', 'Latvia',
       'Lebanon', 'Liberia', 'Liechtenstein', 'Lithuania', 'Luxembourg',
       'Madagascar', 'Malaysia', 'Maldives', 'Malta', 'Mauritania',
       'Mauritius', 'Mexico', 'Moldova', 'Monaco', 'Mongolia',
       'Montenegro', 'Morocco', 'Namibia', 'Nepal', 'Netherlands',
       'New Zealand', 'Nicaragua', 'Niger', 'Nigeria', 'North Macedonia',
       'Norway', 'Oman', 'Pakistan', 'Panama', 'Papua New Guinea',
       'Paraguay', 'Peru', 'Philippines', 'Poland', 'Portugal', 'Qatar',
       'Romania', 'Russia', 'Rwanda', 'Saint Lucia',
       'Saint Vincent and the Grenadines', 'San Marino', 'Saudi Arabia',
       'Senegal', 'Serbia', 'Seychelles', 'Singapore', 'Slovakia',
       'Slovenia', 'Somalia', 'South Africa', 'Spain', 'Sri Lanka',
       'Sudan', 'Suriname', 'Sweden', 'Switzerland', 'Taiwan*',
       'Tanzania', 'Thailand', 'Togo', 'Trinidad and Tobago', 'Tunisia',
       'Turkey', 'Uganda', 'Ukraine', 'United Arab Emirates',
       'United Kingdom', 'Uruguay', 'US', 'Uzbekistan', 'Venezuela',
       'Vietnam', 'Zambia', 'Zimbabwe', 'Dominica', 'Grenada',
       'Mozambique', 'Syria', 'Timor-Leste', 'Belize', 'Laos', 'Libya',
       'West Bank and Gaza', 'Guinea-Bissau', 'Mali',
       'Saint Kitts and Nevis', 'Kosovo', 'Burma', 'Botswana', 'Burundi',
       'Sierra Leone', 'Malawi', 'South Sudan', 'Western Sahara',
       'Sao Tome and Principe', 'Yemen', 'Comoros', 'Tajikistan',
       'Lesotho'], dtype=object)

In [66]:
df_confirmed = df.groupby('Date')['Confirmed'].sum().reset_index()

fig = px.line(df_confirmed, x='Date', y='Confirmed',
              title='Global Trend of Confirmed COVID-19 Cases',
              labels={'Confirmed': 'Confirmed Cases'})
fig.show()

2. Country-Level Trends `(5 pts)`

Select three countries and visualize their confirmed case counts over time on the same plot.

In [67]:
selected_countries = ['China', 'Philippines', 'Singapore']
df_countries = df[df['Country/Region'].isin(selected_countries)]

df_countries_trend = df_countries.groupby(['Date', 'Country/Region'])['Confirmed'].sum().reset_index()

fig = px.line(df_countries_trend,
              x='Date',
              y='Confirmed',
              color='Country/Region',
              title='Confirmed Cases Trend: China vs Philippines vs Singapore')

fig.show()

3. Active vs Recovered `(5 pts)`

For a selected country, create a line chart showing Active and Recovered cases over time.

In [68]:
selected_country = 'China'
df_country_cases = df[df['Country/Region'] == selected_country]

df_trend_active_recovered = df_country_cases.groupby('Date')[['Active', 'Recovered']].sum().reset_index()

fig = px.line(df_trend_active_recovered,
              x='Date',
              y=['Active', 'Recovered'],
              title=f'Active vs. Recovered COVID-19 Cases in {selected_country}',
              labels={'value': 'Number of Cases', 'variable': 'Case Type'})
fig.show()

In [69]:
selected_country = 'Philippines'
df_country_cases = df[df['Country/Region'] == selected_country]

df_trend_active_recovered = df_country_cases.groupby('Date')[['Active', 'Recovered']].sum().reset_index()

fig = px.line(df_trend_active_recovered,
              x='Date',
              y=['Active', 'Recovered'],
              title=f'Active vs. Recovered COVID-19 Cases in {selected_country}',
              labels={'value': 'Number of Cases', 'variable': 'Case Type'})
fig.show()

In [70]:
selected_country = 'Singapore'
df_country_cases = df[df['Country/Region'] == selected_country]

df_trend_active_recovered = df_country_cases.groupby('Date')[['Active', 'Recovered']].sum().reset_index()

fig = px.line(df_trend_active_recovered,
              x='Date',
              y=['Active', 'Recovered'],
              title=f'Active vs. Recovered COVID-19 Cases in {selected_country}',
              labels={'value': 'Number of Cases', 'variable': 'Case Type'})
fig.show()

## B: Comparative Visualizations

4. Country Comparison `(5 pts)`

Using data from a single date, create a bar chart showing the top 10 countries by confirmed cases.

In [113]:
selected_date = df['Date'].max()
df_date = df[df['Date'] == selected_date]

df_date.groupby('Country/Region')['Confirmed'].sum().sort_values(ascending=False)

Country/Region
US                       4290259
Brazil                   2442375
India                    1480073
Russia                    816680
South Africa              452529
                          ...
Dominica                      18
Saint Kitts and Nevis         17
Greenland                     14
Holy See                      12
Western Sahara                10
Name: Confirmed, Length: 187, dtype: int64

In [120]:
top_countries = df_date.groupby('Country/Region')['Confirmed'].sum().nlargest(10).reset_index()

fig = px.bar(top_countries, x='Country/Region', color='Country/Region', y='Confirmed', title=f'Top 10 Countries by Confirmed Cases', labels={'Confirmed': 'Confirmed Cases', 'Country/Region': 'Country'})
fig.show()

5. WHO Region Comparison `(5 pts)`

Aggregate confirmed cases by WHO Region and visualize the result using a bar chart.

In [115]:
df.groupby('WHO Region')['Confirmed'].sum().sort_values(ascending=False)

WHO Region
Americas                 402261194
Europe                   248879793
Eastern Mediterranean     74082892
South-East Asia           55118365
Western Pacific           26374411
Africa                    21791827
Name: Confirmed, dtype: int64

In [118]:
df_who_region_cases = df.groupby('WHO Region')['Confirmed'].sum().reset_index()

fig = px.bar(df_who_region_cases,x='WHO Region', y='Confirmed', color='WHO Region', title='Confirmed Cases by WHO Region', labels={'Confirmed': 'Total Confirmed Cases', 'WHO Region': 'WHO Region'})
fig.show()

## C. Geographic Visualization

6. Geographic Spread `(10 pts)`

Using Latitude and Longitude, create a map-based visualization showing confirmed cases for a selected date.

In [124]:
selected_date = df['Date'].max()
df_latest = df[df["Date"] == selected_date]

fig = px.choropleth(
    df_latest,
    locations="Country/Region",
    locationmode="country names",
    color="Confirmed",
    hover_name="Country/Region",
    projection="natural earth",
    title=f"Global Confirmed Cases in {selected_date}"
)

fig.show()

7. Regional Clustering `(15 pts)`

Create a visualization that shows how confirmed cases are distributed geographically within a single WHO Region.

In [122]:
target_region = 'Americas'
df_region = df[(df["Date"] == selected_date) & (df["WHO Region"] == target_region)]

fig = px.choropleth(
    df_region,
    locations="Country/Region",
    locationmode="country names",
    color="Confirmed",
    hover_name="Country/Region",
    projection="natural earth",
    title=f"Confirmed Cases Distribution in {target_region} Region",
)

fig.show()